# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np
import time

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here
start = time.time()
g = random_integers[0:5]
newlist= g.tolist()

# use for loop and find avg  

thirdcol=[]
for i in range(5):
  p=newlist[i][2]
  thirdcol.append(p)
avgrage_of_3rd_colmn = sum(thirdcol) / len(thirdcol)
# print("The 3th column list",thirdcol)

# use for loop and find avg  

fourthcol=[]
for j in range(5):
  p=newlist[j][3]
  fourthcol.append(p)
avgrage_of_4th_colmn = sum(fourthcol) / len(fourthcol)
# print("The 4th column list",fourthcol)

# print("Average value:-")
# print("Average of 3rd column is:",avgrage_of_3rd_colmn)
# print("Average of 4th column is:",avgrage_of_4th_colmn)
avg = (avgrage_of_4th_colmn+ avgrage_of_3rd_colmn)/2
print("the avgrage is:",avg)
end = time.time()
print(end - start)

the avgrage is: 286058.5
0.0005612373352050781


In [ ]:
start = time.time()
random_integers[:5,2:4].mean()
end = time.time()

print(end - start)

0.0001308917999267578


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
list_inegral = np.random.randint(5,21,(10,2),dtype=int)
list_inegral

array([[15, 20],
       [10,  7],
       [ 6, 16],
       [ 9, 20],
       [ 6, 10],
       [19,  6],
       [13, 17],
       [13, 12],
       [19, 19],
       [ 9,  9]])

In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
start = time.time()
new = list_inegral.tolist()

x_list=[]
for o in new:
  x_list.append(o[0])

y_list=[]
for p in new:
  y_list.append(p[1])

Euclidean_distances=[]

for x in new:
  for y in new:
# Euclidean formula
    Euclidean=np.sqrt((x[0]-y[0])**2 + (x[1]-y[1])**2)
    Euclidean_distances.append(Euclidean)

    
print("X-list-->",x_list)
print("Y list-->",y_list)
Euclidean_distances_pair=np.asarray(Euclidean_distances)
Euclidean_distances_pair

end = time.time()

print(end - start)

X-list--> [15, 10, 6, 9, 6, 19, 13, 13, 19, 9]
Y list--> [20, 7, 16, 20, 10, 6, 17, 12, 19, 9]
0.0018763542175292969


In [ ]:
# np.random.choice([1,2,3],(10,10))

In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
# start = time.time()
Manhattan_distances=[]

for x in new:
  for y in new:

# Euclidean formula
    Manhattan=np.absolute((x[0]-y[0]) + (x[1]-y[1]))
    Manhattan_distances.append(Manhattan)

print("X-list-->",x_list)
print("Y list-->",y_list)
Manhattan_distances_pair=np.asarray(Manhattan_distances)
Manhattan_distances_pair


# end = time.time()

# print(end - start)


X-list--> [15, 10, 6, 9, 6, 19, 13, 13, 19, 9]
Y list--> [20, 7, 16, 20, 10, 6, 17, 12, 19, 9]


array([ 0, 18, 13,  6, 19, 10,  5, 10,  3, 17, 18,  0,  5, 12,  1,  8, 13,
        8, 21,  1, 13,  5,  0,  7,  6,  3,  8,  3, 16,  4,  6, 12,  7,  0,
       13,  4,  1,  4,  9, 11, 19,  1,  6, 13,  0,  9, 14,  9, 22,  2, 10,
        8,  3,  4,  9,  0,  5,  0, 13,  7,  5, 13,  8,  1, 14,  5,  0,  5,
        8, 12, 10,  8,  3,  4,  9,  0,  5,  0, 13,  7,  3, 21, 16,  9, 22,
       13,  8, 13,  0, 20, 17,  1,  4, 11,  2,  7, 12,  7, 20,  0])

## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here

n=np.intersect1d(Euclidean_distances_pair,Manhattan_distances_pair)
n


array([ 0.,  4.,  5.,  6.,  8., 15.])

# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [2]:
# Your code below ..

contiguous_list=[]
big_matrix=np.random.randint(1,100,size=(10,10))
print(big_matrix)
for row in range(0,8):      # for accessing rows one by one
    for col in range(0,8):  # for accessing rows one by one
        contiguous_list.append(big_matrix[row:row+3,col:col+3])

contiguous_array=np.asarray(contiguous_list)

print(contiguous_array)


[[70 96 25 14 58 57 88 30 99  8]
 [99 52 84 15 63 12 51 87 18 42]
 [ 4 95 86 24 75 88  1 98 76 45]
 [99 68 87  9 22  1 16 88 99 15]
 [ 7 79 80 75 58  8 14 30 93 63]
 [50 71 57 14 25  9 34 17 60 29]
 [40 86 47 94 25  7 82 95  8 77]
 [61 36 18 81 89 84  6 34  6 78]
 [ 2 66 31  7 79 57 84 28 90 41]
 [10  9 45 53 49 12 62 46  3 80]]
[[[70 96 25]
  [99 52 84]
  [ 4 95 86]]

 [[96 25 14]
  [52 84 15]
  [95 86 24]]

 [[25 14 58]
  [84 15 63]
  [86 24 75]]

 [[14 58 57]
  [15 63 12]
  [24 75 88]]

 [[58 57 88]
  [63 12 51]
  [75 88  1]]

 [[57 88 30]
  [12 51 87]
  [88  1 98]]

 [[88 30 99]
  [51 87 18]
  [ 1 98 76]]

 [[30 99  8]
  [87 18 42]
  [98 76 45]]

 [[99 52 84]
  [ 4 95 86]
  [99 68 87]]

 [[52 84 15]
  [95 86 24]
  [68 87  9]]

 [[84 15 63]
  [86 24 75]
  [87  9 22]]

 [[15 63 12]
  [24 75 88]
  [ 9 22  1]]

 [[63 12 51]
  [75 88  1]
  [22  1 16]]

 [[12 51 87]
  [88  1 98]
  [ 1 16 88]]

 [[51 87 18]
  [ 1 98 76]
  [16 88 99]]

 [[87 18 42]
  [98 76 45]
  [88 99 15]]

 [[ 4 95 86]


#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [3]:
# Your function below

def get_nearest_value(elem,array):
    """Return the nearest value in the given array for given input"""
    nearest_value = array.flat[np.abs(array - elem).argmin()]                   # flatern and then findind the value with min difrence for given input
    return nearest_value
array=np.random.randint(10,500, size=(1, 15))
print(array)





[[146 248  28  19 260  17 415 255 382 425 195 251 128 258  74]]


In [ ]:
ele=int(input("Enter the element for which you want to find the nearest value for "))
print(f"Nearest point to {ele} is {get_nearest_value(ele,array)}")